spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092 # Optional (default value)
      bindings:
        input:
          destination: cloud-stream-input
          group: spring-cloud-stream-kafka # Optional
          content-type: text/plain
        output:
          destination: cloud-stream-output
          content-type: text/plain
